"""ForwardForwardUpdateRule — Hinton's Forward-Forward algorithm.

Replaces backpropagation with two forward passes on positive and negative data.

Algorithm per step:
    For each layer L:
        goodness(x) = mean(x²)   — sum of squared activations
    Positive pass (real data):   maximise goodness > threshold
    Negative pass (corrupted):   minimise goodness below threshold

Loss per layer:  − log σ(goodness − threshold)  (positive)
                 − log σ(threshold − goodness)  (negative)

In this implementation:
    * The model must be an ``nn.Sequential`` or expose ``.layers`` (each element
      has its own forward).
    * Positive data:  ``batch["input_ids"]`` (or ``batch["x"]``)
    * Negative data:  ``batch.get("neg_input_ids")`` or auto-generated by
      shuffling the batch axis.
    * The final layer uses standard cross-entropy for task evaluation.

Registered as ``@register("update_rule", "forward_forward")``.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any

import torch
import torch.nn as nn
import torch.nn.functional as F

from lighttrain.registry import register


def _current_lr(optimizer: Any) -> float:
    inner = getattr(optimizer, "optimizer", optimizer)
    groups = getattr(inner, "param_groups", None)
    if not groups:
        return 0.0
    return float(groups[0].get("lr", 0.0))


@register("update_rule", "forward_forward")
class ForwardForwardUpdateRule:
    """Forward-Forward algorithm (layer-local learning, no backprop).

    Args:
        threshold:     Goodness threshold separating positive/negative.
        grad_clip:     Gradient norm clip (0 = disabled).
    """

    def __init__(
        self,
        threshold: float = 2.0,
        grad_clip: float = 1.0,
    ) -> None:
        self.threshold = float(threshold)
        self.grad_clip = float(grad_clip)

    def setup(self, model: Any, sample: Any) -> None:  # noqa: ARG002
        return None

    def state_dict(self) -> dict[str, Any]:
        return {"threshold": self.threshold, "grad_clip": self.grad_clip}

    def load_state_dict(self, sd: Mapping[str, Any]) -> None:
        self.threshold = float(sd.get("threshold", self.threshold))
        self.grad_clip = float(sd.get("grad_clip", self.grad_clip))

    def _get_layers(self, model: nn.Module) -> list[nn.Module]:
        for attr in ("layers", "blocks", "children_list"):
            seq = getattr(model, attr, None)
            if seq is not None:
                return list(seq)
        return list(model.children())

    def _goodness(self, h: torch.Tensor) -> torch.Tensor:
        return h.pow(2).mean(dim=-1)  # (B,)

    def _ff_loss(self, h: torch.Tensor, positive: bool) -> torch.Tensor:
        g = self._goodness(h)
        if positive:
            return F.softplus(self.threshold - g).mean()
        else:
            return F.softplus(g - self.threshold).mean()

    def step(
        self,
        model: Any,
        batch: Mapping[str, Any],
        ctx: Any,
    ) -> dict[str, Any]:
        bus = ctx.bus
        optimizer = ctx.optimizer
        scheduler = ctx.scheduler

        if bus is not None:
            bus.dispatch("on_step_begin", step=ctx.step, ctx=ctx, batch=batch)

        ctx.extras["model"] = model

        # Resolve positive and negative inputs
        if "input_ids" in batch:
            pos_input = batch["input_ids"].float() if batch["input_ids"].is_floating_point() else batch["input_ids"].float()
        elif "x" in batch:
            pos_input = batch["x"].float()
        else:
            raise KeyError("ForwardForward: expected 'input_ids' or 'x' in batch.")

        if "neg_input_ids" in batch:
            neg_input = batch["neg_input_ids"].float()
        elif "neg_x" in batch:
            neg_input = batch["neg_x"].float()
        else:
            # Auto-generate negatives by shuffling the batch
            idx = torch.randperm(pos_input.shape[0], device=pos_input.device)
            neg_input = pos_input[idx]

        layers = self._get_layers(model)
        total_loss = torch.zeros(1, device=pos_input.device)
        h_pos = pos_input
        h_neg = neg_input

        for layer in layers:
            # Each layer has its own local optimizer — here we do a joint step.
            h_pos = h_pos.detach()
            h_neg = h_neg.detach()

            # Forward
            h_pos_out = layer(h_pos)
            h_neg_out = layer(h_neg)

            # Flatten for goodness computation
            hp_flat = h_pos_out.view(h_pos_out.shape[0], -1) if h_pos_out.dim() > 2 else h_pos_out
            hn_flat = h_neg_out.view(h_neg_out.shape[0], -1) if h_neg_out.dim() > 2 else h_neg_out

            layer_loss = self._ff_loss(hp_flat, positive=True) + self._ff_loss(hn_flat, positive=False)
            total_loss = total_loss + layer_loss

            # Normalise output for next layer (L2 norm per sample)
            norm = h_pos_out.view(h_pos_out.shape[0], -1).norm(dim=-1, keepdim=True)
            h_pos = (h_pos_out.view(h_pos_out.shape[0], -1) / (norm + 1e-8)).view_as(h_pos_out)
            norm_n = h_neg_out.view(h_neg_out.shape[0], -1).norm(dim=-1, keepdim=True)
            h_neg = (h_neg_out.view(h_neg_out.shape[0], -1) / (norm_n + 1e-8)).view_as(h_neg_out)

        optimizer.zero_grad(set_to_none=True)
        total_loss.backward()

        grad_norm = 0.0
        if self.grad_clip > 0:
            params = [p for p in model.parameters() if p.grad is not None]
            if params:
                gn = torch.nn.utils.clip_grad_norm_(params, self.grad_clip)
                grad_norm = float(gn)

        if bus is not None:
            bus.dispatch("on_optimizer_step_pre", step=ctx.step)

        optimizer.step()
        optimizer.zero_grad(set_to_none=True)

        if bus is not None:
            bus.dispatch("on_optimizer_step_post", step=ctx.step, model=model)

        if scheduler is not None and getattr(scheduler, "step_per_batch", True):
            scheduler.step()

        ctx.metrics["loss"] = float(total_loss.detach().item())
        ctx.metrics["grad_norm"] = grad_norm
        ctx.metrics["lr"] = _current_lr(optimizer)
        ctx.metrics["skipped"] = 0.0

        if bus is not None:
            bus.dispatch("on_step_end", step=ctx.step, metrics=ctx.metrics, batch=batch, model=model)

        return dict(ctx.metrics)


__all__ = ["ForwardForwardUpdateRule"]
