"""Hypothesis logging.

A lightweight structured log for experiment hypotheses.  Each entry records
what you expected to happen and a reference to the run that tested it so
``compare`` can later pull the actual outcome.

Usage::

    from lighttrain.lab.hypothesis import HypothesisLog

    log = HypothesisLog(Path("runs/my_exp/hypotheses.jsonl"))
    log.add("Reducing LR by 10x will improve val_loss", run_dir=run_a)
    # … after the run …
    log.update(0, outcome="val_loss went from 2.3 → 2.1, confirmed")
    print(log.render_markdown())
"""

from __future__ import annotations

import json
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path

_TEMPLATE = """\
# Hypothesis log

Generated by `lighttrain lab`.

## Entries

{entries}

---
_Add new hypotheses with `HypothesisLog.add()` or edit this file._
"""


@dataclass
class HypothesisEntry:
    id: int
    hypothesis: str
    run_dir: str | None = None
    added_ts: float = field(default_factory=time.time)
    outcome: str | None = None
    resolved_ts: float | None = None
    tags: list[str] = field(default_factory=list)


class HypothesisLog:
    """Append-only log of experiment hypotheses backed by a JSONL file."""

    def __init__(self, path: Path) -> None:
        self.path = Path(path)
        self._entries: list[HypothesisEntry] = []
        if self.path.exists():
            self._load()

    def _load(self) -> None:
        with open(self.path, encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    d = json.loads(line)
                    self._entries.append(HypothesisEntry(**d))
                except (json.JSONDecodeError, TypeError):
                    continue

    def _save(self) -> None:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        with open(self.path, "w", encoding="utf-8") as f:
            for e in self._entries:
                f.write(json.dumps(asdict(e)) + "\n")

    def add(
        self,
        hypothesis: str,
        *,
        run_dir: Path | str | None = None,
        tags: list[str] | None = None,
    ) -> int:
        """Append a new hypothesis; returns its id."""
        entry = HypothesisEntry(
            id=len(self._entries),
            hypothesis=hypothesis,
            run_dir=str(run_dir) if run_dir is not None else None,
            tags=list(tags or []),
        )
        self._entries.append(entry)
        self._save()
        return entry.id

    def update(
        self,
        hypothesis_id: int,
        *,
        outcome: str | None = None,
        run_dir: Path | str | None = None,
    ) -> None:
        """Update an existing entry with an outcome."""
        for e in self._entries:
            if e.id == hypothesis_id:
                if outcome is not None:
                    e.outcome = outcome
                    e.resolved_ts = time.time()
                if run_dir is not None:
                    e.run_dir = str(run_dir)
                break
        self._save()

    def render_markdown(self) -> str:
        """Return a Markdown representation of all entries."""
        if not self._entries:
            return _TEMPLATE.format(entries="_No hypotheses logged yet._")
        parts: list[str] = []
        for e in self._entries:
            status = "✅ resolved" if e.outcome else "⏳ pending"
            lines = [
                f"### #{e.id} — {status}",
                f"**Hypothesis:** {e.hypothesis}",
            ]
            if e.run_dir:
                lines.append(f"**Run:** `{e.run_dir}`")
            if e.outcome:
                lines.append(f"**Outcome:** {e.outcome}")
            if e.tags:
                lines.append(f"**Tags:** {', '.join(e.tags)}")
            parts.append("\n".join(lines))
        return _TEMPLATE.format(entries="\n\n".join(parts))

    def write_markdown(self, out_path: Path | None = None) -> Path:
        if out_path is None:
            out_path = self.path.with_suffix(".md")
        out_path = Path(out_path)
        out_path.write_text(self.render_markdown(), encoding="utf-8")
        return out_path

    def __len__(self) -> int:
        return len(self._entries)

    def __iter__(self):  # type: ignore[override]
        return iter(self._entries)


__all__ = ["HypothesisLog", "HypothesisEntry"]
